public class BigMachinesParameters {
    
    // BigMachines parameters
    public static Boolean usesSSL =       true; // does BigMachines site use SSL?
    public static String bm_site =        'incontact'; // subdomain of BigMachines site
    public static String process_id =     '4133539'; // id of commerce process
    public static String action_id_copy = '4134832'; // id of commerce process's copy action
    public static String action_id_open = '4134812'; // id of commerce process's open action
    public static String document_id =    '4133603'; // id of main document in commerce process
    public static String version_id =     '4135947'; // version id    
    public static String process_var =    'quotes_process_bmClone_14'; // variable name of commerce process

}