/**
 * Created by william.nelson on 11/30/2016.
 */
public class ChartData2
{
	public string  ProjectId {get; set;}
    public string  ProjectName {get; set;}
    public Date EndDate {get; set;}
    public Date StartDate {get; set;}
    public integer DurationDays{get; set;}
    public decimal PercentComplete{get; set;}
    public string TShirtSize{get; set;}
    public string ProjectManager{get; set;}
    public string ProjectStatus{get; set;}
    public string ProductChannel{get;set;}
    public string Team{get;set;}
    public string TeamColor{get;set;}
    public string ProgramColor{get;set;}
    public string ProductChannelFullName{get;set;}

}